spring:
  application:
    name: "Weather App"
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
weather-service:
  url: https://api.open-meteo.com/v1/forecast
preferences:
  defaults:
    units: metric